### ISSUE TITLE
Crashes semantic release v15

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/github-post-release#24]
with message
```
[Semantic release]: An error occurred while running semantic-release: { TypeError: Cannot read property 'repository' of undefined
    at githubPostRelease (/home/travis/build/bahmutov/snap-shot-it/node_modules/github-post-release/src/index.js:123:23)
    at Object.defineProperty (/home/travis/build/bahmutov/snap-shot-it/node_modules/semantic-release/lib/plugins/normalize.js:44:30)
```
for example https://travis-ci.org/bahmutov/snap-shot-it/builds/352854491

**Comment by chrisbreiding** [comment]
FWIW, this seems to originate in semantic-release v11.
