### ISSUE TITLE
Make repo url https

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/github-post-release#6]
Otherwise, if the url is `repo url git+https://github.com/bahmutov/github-post-release.git` for example, it cannot load the module to follow redirects when trying to call from `github` module! 😟

Example CI output https://travis-ci.org/bahmutov/github-post-release/builds/251286225

```
{ version: '3.0.0',
  port: null,
  protocol: 'git+https',
  host: 'github.com' }
Could not comment on issue 1
{ Error: Cannot find module 'follow-redirects/git+https'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at httpSendRequest (/home/travis/build/bahmutov/github-post-release/node_modules/github/lib/index.js:774:23)
```

**Comment by bahmutov** [comment]
Relevant code that blindly autoloads module to follow redirects 
```js
var reqModule = self.config.followRedirects === false ? protocol : 'follow-redirects/' + protocol;
```
